### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'lower'

### ISSUE THREAD

**Issue by scmanjarrez** [ShawnDEvans/smbmap#101]
Hi, thanks for your amazing tool.
I've found this error while running both, smbmap 1.9.2 and 1.10.4:

```
SMBMap - Samba Share Enumerator v1.10.4 | Shawn Evans - ShawnDEvans@gmail.com<mailto:ShawnDEvans@gmail.com>
                     https://github.com/ShawnDEvans/smbmap

[*] Detected 1 hosts serving SMB                                                                                                  
[*] Established 1 SMB connections(s) and 1 authenticated session(s)                                                      
Falsenumerating shares...                                                                                                    
False
False
Traceback (most recent call last):
  File "/home/kali/htb/tools/smbmap/venv/bin/smbmap", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kali/htb/tools/smbmap/venv/lib/python3.11/site-packages/smbmap/smbmap.py", line 1552, in main
    elif host_shares[host][share_name]['privs'] != 'NO ACCESS' and share_name.lower() == lsshare.lower():
                                                                                         ^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'lower'
```

The `False` prints are just debug prints I put to obtain the value of lsshare and check why it was throwing an error.

**Comment by ShawnDEvans** [comment]
Thanks! I'll look into it.

**Comment by labor4** [comment]
me too!

**Comment by ShawnDEvans** [comment]
Could you post the command that yielded that error? I think I know what's up

**Comment by labor4** [comment]
`smbmap -q --no-banner --no-color --no-update -H $SERVER -u $MYLOGIN -p $MYPASS --dir-only --csv /tmp/tmp_$$.csv 1>/dev/null`

**Comment by ShawnDEvans** [comment]
I just noticed that this issue was in reference to v1.10.4. I would recommend trying the command in the latest release. There have been many big fixes and improvements made, which may address your issue. If you continue to experience the same behavior, please do report back. Thanks!
